on:
  push:
    branches:
      - master

name: 🚀 Deploy website on push

jobs:
  web-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: www.escleroptica.com
          username: carlos@sistema.escleroptica.com
          password: carlosangulo1234
          exclude: |
            # Carpetas que NO quieres subir
            storage/**
            vendor/**
            node_modules/**
            # Archivos ocultos y .git
            **/.git*
            **/.git*/**
            # Archivos que no quieres sobrescribir
            .env
            .env.example
            .editorconfig
            .gitattributes
            .gitignore
            .styleci.yml
            artisan
            composer.json
            composer.lock
            package-lock.json
            package.json
            phpunit.xml
            README.md
            server.php
            tailwind.config.js
            webpack.mix.js
          method: ftp
